- .github/workflows/pathogen-repo-ci.yaml
- workflow-templates/pathogen-repo-ci.properties.json
- workflow-templates/pathogen-repo-ci.yaml
The goal is to establish a common setup for CI for all or at least most
of our pathogen build repos.
Includes a reusable workflow¹ which can be called/invoked by our
workflows in other repos and a "starter" workflow template² that
performs such a call, for copying into the pathogen repo (either
manually or via the web UI which supports these starter workflows).
These are both basic for now but appropriate for our "simple" pathogen
builds like zika and measles.  We can add workflow parameters and
conditionals as necessary in the future to support CI for more complex
builds, like ncov.  (It won't take much!)
Related to <https://github.com/nextstrain/zika/pull/16>.
¹ https://docs.github.com/en/actions/using-workflows/reusing-workflows
² …
> Workflows for basic pathogen repo CI

- .github/workflows/pathogen-repo-ci.yaml
Additional build args are needed for avian-flu and seasonal-flu repos.
Related to https://github.com/nextstrain/avian-flu/pull/8 and https://github.com/nextstrain/seasonal-flu/pull/80
> Parameterize pathogen repo CI with optional additional `nextstrain build` args

- .github/workflows/ci.yaml
- actions/setup-nextstrain-cli/action.yaml
Standardize and centralize how our workflows setup a working copy of
`nextstrain` when that's all they need.  This makes maintenance of the
setup much easier.
Investigating <https://github.com/nextstrain/cli/issues/171> made me
realize we could standardize this for basic workflows that require
`nextstrain`.
> Add a shared setup-nextstrain-cli action for our GitHub Actions workflows

- .github/workflows/ci.yaml
- .github/workflows/pathogen-repo-ci.yaml
- workflow-templates/pathogen-repo-ci.properties.json
Assume that if it's missing there's no data setup to do.  Lets us use
this workflow for the ncov repo, which doesn't use example_data/.
Related to …
> pathogen-repo-ci: Make example_data/ optional

- .github/workflows/ci.yaml
- .github/workflows/pathogen-repo-ci.yaml
- actions/setup-nextstrain-cli/action.yaml
Use the new `setup-nextstrain-cli` action in this repo in the `pathogen-repo-ci` reusable workflow. Further standardizes and centralizes this. This sort of workflow is exactly one of the intended use cases for the setup action.
Also adds CI testing of the `pathogen-repo-ci` workflow for this repo, which is useful for making sure updates to it work before they're merged.
Related to #17.
> Use `setup-nextstrain-cli` action in `pathogen-repo-ci` workflow and test the workflow

- .github/workflows/pathogen-repo-ci.yaml
Seems likely to be useful at times for debugging why a CI run failed.
Based on #18 so I can see it run in this repo's CI before merge. [Update: …and glad I did, as it caught a typo!]
> Upload auspice/, results/, and Snakemake logs from pathogen repo CI runs to artifact storage

- .github/workflows/docs-ci.yaml
- workflow-templates/docs-ci.properties.json
- workflow-templates/docs-ci.yaml
- workflow-templates/pathogen-repo-ci.yaml
This parallels the motivation behind 6245d9e4d031a244d32979e4a27c6badcb503854 for pathogen repo CI, but for repos containing Sphinx documentation.
As a starting point, the reusable workflow fails on build warnings such as invalid links and bad formatting.
_N/A_
See nextstrain/ncov#941
> Workflows for Sphinx docs CI

- workflow-templates/docs-ci.yaml
- workflow-templates/pathogen-repo-ci.yaml
The "with" parameter block was added to the wrong file in "Workflows for
Sphinx docs CI" (a65c1b2).
Related to #20.
> Fix workflow-templates mixup between docs-ci and pathogen-repo-ci

- .github/workflows/pathogen-repo-ci.yaml
This can be useful to set variables respected by Augur, Nextstrain CLI,
etc.  Implemented ourselves as a workflow input since the usual job.env
block is not (yet?) supported by GitHub Actions for jobs which call a
reusable workflow.
The input value is a YAML-formatted string, which you can easily produce
by pretending you're writing normal nested YAML within a literal
multi-line block scalar (introduced by "|"):
```yaml
with:
env: |
FOO: bar
I_CANT_BELIEVE: "it's not YAML"
```
When (if?) the usual job.env block is supported for reusable workflows,
it will be a small transformation for each caller to use it.
Tested in a separate GitHub Actions testbed, though I may have mucked up the syntax in this particular file. We'll see when I try to use it!
Update: Usage in …
> pathogen-repo-ci: Allow caller to pass env vars

- .github/workflows/pathogen-repo-ci.yaml
Helpful for debugging.  Suggested here by @corneliusroemer.  Based on
similar logic I made for nextstrain.org CI.¹
¹ https://github.com/nextstrain/nextstrain.org/commit/017f1239
> pathogen-repo-ci: Always upload outputs even on failure

- .github/workflows/sync-rtd-redirects.yaml
- workflow-templates/sync-rtd-redirects.yaml
This accomplishes two important things:
1. It protects against misconfigurations of the calling workflow's triggers, e.g. previously if the calling workflow included "pull_request" events then syncs would happen when they shouldn't have because triggers were trusted to be correct.
2. It makes this workflow useful for PRs by previewing the changes that will happen upon merge.
#30
> sync-rtd-redirects: Perform dry runs when not on the default branch

- .github/workflows/ci.yaml
- .github/workflows/docs-ci.yaml
Some docs projects use pip instead of conda to set up the environment.
1. Make environment-file input (Conda setup) optional.
2. Add a new optional input to install from pip.
3. Use one job per environment setup option.
Specifying none of the setup options will cause both jobs to be skipped, but I think that's appropriate user error.
- Closes #21
> docs-ci: Add pip install option

- README.md
- actions/setup-ssh/README.md
- actions/setup-ssh/action.yaml
- actions/setup-ssh/connection-info
- actions/setup-ssh/debug-info
- actions/setup-ssh/setup-keys
- actions/setup-ssh/setup-tailscale
- actions/setup-ssh/wait-for-continue
- devel/check-readme
- workflow-templates/debugging-runner.properties.json
- workflow-templates/debugging-runner.yaml
Useful for debugging issues with GitHub Actions workflows, particularly in cases when similar commands work on your machine but not the runner machines.
See also [the README](https://github.com/nextstrain/.github/blob/actions/setup-ssh/actions/setup-ssh/README.md).
- https://github.com/nextstrain/private/pull/72
> actions/setup-ssh: Direct access to runner machines over Tailscale

- README.md
- actions/setup-debugger/README.md
- actions/setup-debugger/action.yaml
- actions/setup-debugger/debugger
- devel/check-readme
Interception is still slightly flaky at times for as-of-yet unclear reasons, but overall it works!  This is a quick initial implementation to see if such a debugger is actually useful in practice.  There are alternative ways to accomplish the ~same functionality, which I'll describe elsewhere later (and one of which I've prototyped).  One of those may ultimately be a better choice if this debugger does prove its worth.
> actions/setup-debugger: Interactively inspect and manipulate steps of a workflow job

- .github/workflows/pathogen-repo-ci.yaml
See commit messages.
Related-to: <https://github.com/nextstrain/docker-base/pull/148>
> pathogen-repo-ci: Log in to docker.io and ghcr.io if possible

- .github/workflows/ci.yaml
- .github/workflows/pathogen-repo-ci.yaml
Allows calling workflows to succeed even if the job in this called workflow fails.  This is a workaround for the calling working being unable to specify continue-on-error itself.¹
Related-to: <https://github.com/nextstrain/docker-base/pull/148>
¹ <https://docs.github.com/en/actions/using-workflows/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow>
> pathogen-repo-ci: Support a continue-on-error pass thru

- .github/workflows/ci.yaml
- .github/workflows/pathogen-repo-ci.yaml
@victorlin pointed out¹ that we could launder access to the secrets context thru the step env context without the need for an extra step.
I avoid putting the secret itself into the environment (which only increases its potential visibility) and put only its presence/absence instead.
¹ <https://github.com/nextstrain/.github/pull/38#discussion_r1190281387>
> pathogen-repo-ci: Avoid the secret-check step before docker.io login

- .github/workflows/pathogen-repo-ci.yaml
- actions/setup-nextstrain-cli/action.yaml
> pathogen-repo-ci: Multi-runtime

- .github/workflows/pathogen-repo-ci.yaml
Prevents individual runtime failures from interfering with other runtime builds.
Motivated by seasonal-flu CI failure in conda runtime that canceled the job in docker runtime.¹
¹ https://github.com/nextstrain/seasonal-flu/actions/runs/4961494826
Follow up of https://github.com/nextstrain/.github/pull/42
> pathogen-repo-ci: set build matrix to `fail-fast:false`

- .github/workflows/pathogen-repo-ci.yaml
- actions/setup-nextstrain-cli/action.yaml
There's a weird issue with the Conda runtime where the inital setup
uses an older version.¹ Do an update of the default runtime after setup
to ensure we are using the latest version.
We could remove this extra step after we rework `nextstrain setup` to
use the same logic as `nextstrain update`.
¹ https://github.com/nextstrain/monkeypox/issues/177
> Setup nextstrain cli update

- .github/workflows/pathogen-repo-ci.yaml
- actions/setup-nextstrain-cli/action.yaml
I missed in https://github.com/nextstrain/.github/pull/48 that the command `nextstrain update` will exit with error for aws-batch and ambient runtimes. Instead of maintaining a list of runtime to run the update command, just allow it to continue-on-error.
I [found this error](https://github.com/nextstrain/forecasts-ncov/actions/runs/6089488339/job/16522370819#step:4:272) in separate work to update forecasts-ncov to use the pathogen-repo-build workflow with the aws-batch runtime.
> setup-nextstrain-cli: allow nextstrain update to continue-on-error

- .github/workflows/pathogen-repo-build.yaml
Previous pattern expected the AWS Batch job id to be in the example re-attaching command that is only output by the Nextstrain CLI when running the job with the `--detach` flag.
This checks for the AWS Batch job id in the stage output from the CLI immediately after the job was successfully submitted to AWS Batch.¹ This output exists regardless of the detachment status.
¹ https://github.com/nextstrain/cli/blob/3c93e87c2ac6bdd1b6a913070f709067b29a6cc1/nextstrain/cli/runner/aws_batch/__init__.py#L258
Resolves https://github.com/nextstrain/.github/issues/50
> pathogen-repo-build: update AWS Batch job id matching

- .github/workflows/pathogen-repo-ci.yaml
Current `pathogen-repo-ci` seems to assume that we don't need to customize workdir in `nextstrain build .`, i.e. we can't set `nextstrain build foobar`.
Our nextstrain/pathogen-repo-template, however, puts the main workflow in a folder. So we should add that feature.
See https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1695664810319929 for discussion
It works: https://github.com/nextstrain/monkeypox/actions/runs/6303654582/job/17113366921
> feat(pathogen-repo-ci): allow configuration of workflow root

- .github/workflows/pathogen-repo-ci.yaml
- actions/setup-nextstrain-cli/action.yaml
Follow-up to https://github.com/nextstrain/.github/pull/49#issuecomment-1734490175
> setup-nextstrain-cli: Remove unnecessary nextstrain update

- .github/workflows/pathogen-repo-build.yaml
The default role has a pretty limited set of permissions right now: basically only those required to submit and interact with AWS Batch jobs, but not, for example, permissions to upload to our production S3 buckets.  The permissions will probably need to be extended in the future as repos/builds opt into this workflow and this role assumption. The role's trust policy will also need to be extended to allow other repos to assume it.
While the role is currently manually managed, it should really be managed by a Terraform configuration (but one separate from the current nextstrain.org Terraform configurations).
Related-to: <https://github.com/nextstrain/private/issues/22>
> pathogen-repo-build: Support assuming an AWS role via GitHub Actions' OIDC provider

- .gitattributes
- .github/workflows/ci.yaml
- .github/workflows/pathogen-repo-build.yaml
- .github/workflows/pathogen-repo-build.yaml.in
- Makefile
- README.md
- devel/check-readme
- devel/explode-yaml
- devel/pre-commit
- devel/regenerate-workflow
This avoids the disconnect between the success/failure status of a GitHub Actions workflow run and the actual AWS Batch job, which makes for easier reporting and debugging and generally less cognitive dissonance.
GitHub Actions workflow *runs* have a very high max timeout of 35 days, but each *job* in a workflow has a much lower max timeout of 6 hours. Many of our builds should be less than 6 hours¹, but here we support builds up to 24 hours by chaining together 4 GitHub Actions jobs. We can add more jobs to the chain if we need to, but I don't foresee that.
Nearly all of our builds are in public repos, which means they won't consume usage minutes from our GitHub Actions quota. However, they *will* consume concurrency limits from the quota. We were already frequently bumping into the …
> pathogen-repo-build: Wait for AWS Batch jobs to finish

- .github/workflows/ci.yaml
- .github/workflows/pathogen-repo-ci.yaml
- actions/setup-nextstrain-cli/action.yaml
Simplifies and speeds up installation. Aligns with our recommended installation used by many users and many of ourselves. Drops the baggage of setting up a Python install as a side-effect. Discussed on Slack a while back.¹
In order to continue supporting PEP 440/508 (i.e. Pip-style) version range constraints in the cli-version input, I added support for those to the https://nextstrain.org/cli/download/... endpoint.²
I've audited all existing callsites I could find, internally and externally, for transitive reliance on the setup-python step. None seemed to rely upon it, so it's now gone. See also the added comment about removing the python-version input.
¹ <https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1694627907115309>
² <https://github.com/nextstrain/nextstrain.org/pull/797>
> setup-nextstrain-cli: Use a standalone installation instead of Pip/PyPI

- .github/workflows/pathogen-repo-build.yaml
- .github/workflows/pathogen-repo-build.yaml.in
Ran into a workflow run where the `run-build` step failed and the job exited without generating the AWS Batch Job ID or summary.¹
This commit updates the condition to always try to generate the AWS Batch ID as long as the runtime is `aws-batch` and the `build.log` file exists. This then allows the workflow to always generate the AWS Batch Job summary even if the build failed.
¹ https://github.com/nextstrain/forecasts-ncov/actions/runs/8203385071
> pathogen-repo-build: always generate AWS Batch Job ID & summary

- .github/workflows/pathogen-repo-build.yaml
- .github/workflows/pathogen-repo-build.yaml.in
See commit for details.
Resolves #77
> pathogen-repo-build: Move `build.log` to ignored directory

- .github/workflows/pathogen-repo-build.yaml
- .github/workflows/pathogen-repo-build.yaml.in
Ensure support for pathogen repo builds with the latest changes:
* support for workflows in subdirectories¹
* support for setting runtime envvars via `NEXTSTRAIN_RUNTIME_ENVDIRS`²
¹ <https://github.com/nextstrain/cli/releases/tag/8.2.0> 
² <https://github.com/nextstrain/cli/releases/tag/8.3.0>
Related to https://github.com/nextstrain/private/issues/96#issuecomment-2078310852
> pathogen-repo-build: Bump minimum Nextstrain CLI version to 8.3.0

- .github/workflows/ci.yaml
Per Jover,
> This is testing the workaround for continue-on-error added in #40
> works as expected. Reading through that discussion again, @tsibley
> had noted that we can eventually remove the test.
> The workaround has been working for a ~year now, so I think it's 
> safe to remove the test now!
> Remove intentional failure test #48 #58

- .github/workflows/pathogen-repo-build.yaml
- .github/workflows/pathogen-repo-build.yaml.in
- README.md
- bin/write-envdir
Assumes repo-specific roles, `GitHubActionsRoleNextstrainRepo@zika` for example, which are managed by the Terraform configuration in the nextstrain/infra repo.  The repo here is always the _calling_ repository, regardless of if the "repo" input was provided to use workflows from another place.
The runtime credentials are then saved in an envdir that is passed to the build command via `NEXTSTRAIN_RUNTIME_ENVDIRS`.
Namespaced `NEXTSTRAIN_RUNTIME_ENVDIR` with `./git/nextstrain` as suggested by @tsibley in review¹
¹ <https://github.com/nextstrain/.github/pull/81#discussion_r1602240011>
Related-to: <https://github.com/nextstrain/infra/issues/4>
Co-authored-by: Thomas Sibley <tsibley@fredhutch.org>
> pathogen-repo-build: support assuming AWS role for runtime permissions 

- bin/write-envdir
Eventually I'll dust off my WIP for `nextstrain write-envdir` which does this sort of nicety and more, and this Bash program will become obsolete.
> write-envdir: Explicitly error with a better message when a requested var is unset

- .github/workflows/pathogen-repo-build.yaml
- .github/workflows/pathogen-repo-build.yaml.in
No AWS_SESSION_TOKEN is present when callers provide static IAM user credentials via AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. `write-envdir` requires all env vars given are defined.
> pathogen-repo-build: Only write AWS_SESSION_TOKEN into the envdir if it's not empty

- actions/shellcheck/extract-shell-from-gh-actions-files
- actions/shellcheck/extract-shell-from-gh-workflow
- actions/shellcheck/shellcheck
> actions/shellcheck: Check GitHub Actions composite actions too

- .github/workflows/ci.yaml
- .github/workflows/pathogen-repo-ci.yaml
- actions/run-nextstrain-ci-build/action.yaml
Make the CI fail if it doesn't try to run at least one build step, as that's an indication that somebody is trying to use "modern" `pathogen-repo-ci` on an un-modernized pathogen repo (or there's some other grievous misconfig happening).  
#92
> Make `pathogen-repo-ci` fail when config is missing or no builds are attempted

- .github/workflows/pathogen-repo-ci.yaml
- .github/workflows/pathogen-repo-ci.yaml.in
- text-templates/pathogen-repo-ci.md
In testing it's helpful to report all test results even in the face of an early failure to reduce the chances of playing whack-a-mole with unreported failures once when you fix the first failure.  For example, we want to know if the phylogenetic workflow fails even when the ingest workflow run before it fails.
> pathogen-repo-ci: Keep running even if one of the pathogen workflows fails

- .github/workflows/pathogen-repo-ci.yaml
- .github/workflows/pathogen-repo-ci.yaml.in
While "continue-on-error: true" resulted in the behaviour we wanted, it also meant the job step status indicators were misleading: even when an ingest/phylogenetic/nextclade step failed, the UI showed a check mark for them in the logs.  Instead of masking failures to keep going in the face of errors, override the default success() conditional by specifying our own conditions on a status expression.
Related-to: <https://github.com/nextstrain/.github/pull/98#issuecomment-2168846812>
> pathogen-repo-ci: Use status functions in conditionals instead of continue-on-error: true

- .github/workflows/ci.yaml
- .github/workflows/pathogen-repo-build.yaml
- .github/workflows/pathogen-repo-build.yaml.in
Small improvements to the `pathogen-repo-build` workflow. 
Resolves #79 
Resolves #97
> `pathogen-repo-build` improvements

- .github/workflows/docs-ci.yaml
Adds a `make linkcheck` step to the Sphinx CI.
Note that this blocks on the various PRs attached to nextstrain/docs.nextstrain.org#14 — those PRs should be merged before this one.
Update to add: I realized this workflow is used by more than `docs.nextstrain.org`, so before this can be merged, the following repos need to be audited for broken links:
Closes #29 
nextstrain/docs.nextstrain.org#14
> Add `make linkcheck` step, to check external links [#29]

- .github/workflows/docs-ci.yaml
linkcheck [errors on both timeouts and broken links](https://github.com/sphinx-doc/sphinx/blob/2f1d775dfda9e4f81dfff6cfbe9edf7731e32a97/sphinx/builders/linkcheck.py#L82-L83). We only want the CI job to fail on broken links since timeouts are most likely transient.
- #106
- https://github.com/nextstrain/docs.nextstrain.org/pull/232
- https://github.com/nextstrain/augur/pull/1650
> docs-ci: Don't error on timeouts

- .github/workflows/docs-ci.yaml
These are marked as optional in the inputs block. There was an implicit assumption that it's required to have one of the inputs but not both. This can't be encoded in the inputs block so check the values as the very first step.
- Follow-up to https://github.com/nextstrain/.github/pull/109#discussion_r1803510032
> docs-ci: Check environment-file and pip-install-target inputs

- .github/workflows/keep-workflows-enabled.yaml
- README.md
Uses the GH API to "enable" scheduled workflows on the first of
every month as a work-around for scheduled workflows being automatically
disabled when no repository activity has occurred in 60 days.
Included all active Nextstrain org GH Action workflows that have the
`schedule` trigger plus this new workflow so it keeps itself enabled.
<https://github.com/search?q=org%3Anextstrain+path%3A.github%2Fworkflows%2F**+schedule&type=code>
Resolves https://github.com/nextstrain/.github/issues/112
> Keep workflows enabled

- .github/workflows/keep-workflows-enabled.yaml
Noticed that hmpv's "Ingest to phylogenetic" workflow was disabled since 2025-03-10. I've manually re-enabled the workflow and adding it here to ensure the workflow stays enabled even if there's no activity in the repo.
Outside of this PR, I had to add nextstrain/core to the hmpv repo so that nextstrain-bot's GH token had permissions to enable the workflow. 
Resolves <https://github.com/nextstrain/.github/issues/123>
> keep-workflows-enabled: Add hmpv

- .github/workflows/pathogen-repo-build.yaml
- .github/workflows/pathogen-repo-build.yaml.in
Nextstrain CLI 9.0.0 added an improvement that automatically disables colorized and bolded output when stdout is not a terminal (or when NO_COLOR is set).  This broke our sed pattern which too-stringently expected ANSI escapes (matched by ".+") to surround the "AWS Batch Job ID:" label.
Bump our CLI requirement to 9.0.0 and remove expectation of ANSI escapes from the sed pattern.  We could handle both presence and absence of ANSI escapes, but its simpler to bump to 9.0.0 and expect absence.
In the future, we should stop parsing job logs and add a feature to Nextstrain CLI to directly emit this job id in a more structured way.
Related-to: <https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1743179523144269>
> pathogen-repo-build: Fix extraction of AWS Batch job ids

- .github/workflows/keep-workflows-enabled.yaml
hmpv, nipah, and oropouche have all been updated to scheduling the ingest  workflow according to 
<https://github.com/nextstrain/pathogen-repo-guide/issues/25>
> keep-workflows-enabled: update `ingest-to-phylogenetic` to `ingest`
